#!/usr/bin/env python
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from chartvqa.badcase import analyze_badcases


CASE_LABELS = {
    "lora_improved": "LoRA 改进",
    "lora_regressed": "LoRA 退化",
    "both_correct": "两者都对",
    "both_wrong": "两者都错",
}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze base vs LoRA badcases from an evaluation CSV."
    )
    parser.add_argument(
        "--input-csv",
        default="reports/eval_lora_1epoch_results.csv",
        help="Evaluation CSV generated by scripts/run_eval.py.",
    )
    parser.add_argument(
        "--output-md",
        default="reports/badcase_analysis.md",
        help="Markdown report path.",
    )
    parser.add_argument(
        "--max-cases",
        type=int,
        default=20,
        help="Maximum detailed cases to include.",
    )
    return parser.parse_args(argv)


def _read_rows(path: str | Path) -> list[dict[str, str]]:
    with Path(path).open("r", encoding="utf-8", newline="") as file:
        return list(csv.DictReader(file))


def render_markdown(analysis: dict[str, Any], max_cases: int = 20) -> str:
    lines = [
        "# Badcase 分析",
        "",
        "## 汇总",
        "",
        "| 类型 | 数量 |",
        "|------|------|",
    ]
    summary = analysis["summary"]
    for key in ("lora_improved", "lora_regressed", "both_correct", "both_wrong"):
        lines.append(f"| {CASE_LABELS[key]} | {summary.get(key, 0)} |")

    lines.extend(
        [
            "",
            "## 重点样本",
            "",
        ]
    )

    priority = {"lora_improved": 0, "lora_regressed": 1, "both_wrong": 2, "both_correct": 3}
    cases = sorted(
        analysis["cases"],
        key=lambda item: (priority.get(item["case_type"], 99), int(item["index"])),
    )
    for case in cases[:max_cases]:
        lines.extend(
            [
                f"### 样本 {case['index']}：{CASE_LABELS[case['case_type']]}",
                "",
                f"- 问题：{case['question']}",
                f"- 标准答案：{case['answer']}",
                f"- base：{case['base_prediction']}",
                f"- LoRA：{case['lora_prediction']}",
                f"- base 错误类型：{case['base_error_type']}",
                f"- LoRA 错误类型：{case['lora_error_type']}",
                "",
            ]
        )

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    rows = _read_rows(args.input_csv)
    analysis = analyze_badcases(rows)
    markdown = render_markdown(analysis, max_cases=args.max_cases)

    output_path = Path(args.output_md)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown + "\n", encoding="utf-8")
    print(f"wrote badcase report: {output_path}")


if __name__ == "__main__":
    main()
